name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: vds2414219

    strategy:
      matrix:
        java-version: [ 17, 21 ]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
